default: &default

development:
  <<: *default
  hosts:
    web:
      host: www.localhost.com
      url: http://www.localhost.com
    auth:
      host: auth.localhost.com
      url: http://auth.localhost.com
    visit:
      host: www.localhost.com
      url: http://www.localhost.com
    page:
      host: www.localhost.com
      url: http://www.localhost.com
    content:
      host: www.localhost.com
      url: http://www.localhost.com

test:
  <<: *default

production:
  <<: *default
  hosts:
    web:
      host: www.x-history.top
      url: http://www.x-history.top
    auth:
      host: auth.x-history.top
      url: http://auth.x-history.top
    visit:
      host: visit.x-history.top
      url: http://visit.x-history.top
    page:
      host: page.x-history.top
      url: http://page.x-history.top
    content:
      host: content.x-history.top
      url: http://content.x-history.top

