default: &default

development:
  <<: *default
  http_triggers:
    self: http://localhost:13000/

test:
  <<: *default

production:
  <<: *default
  http_triggers:
    self: http://visithistory.x-history.top/

